<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TemplateBlockRequest;
use App\Models\CertificateTemplate;
use App\Models\TemplateBlock;
use App\Services\TemplateService;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Storage;

class TemplateBlockController extends Controller
{
    public function __construct(private readonly TemplateService $templates) {}

    public function store(TemplateBlockRequest $request, CertificateTemplate $template): JsonResponse
    {
        $data = $request->safe()->except('image');

        if ($request->hasFile('image')) {
            $data['value'] = $request->file('image')->store('blocks', 'public');
            $data['is_dynamic'] = false;
        } elseif (($data['is_dynamic'] ?? false) && empty($data['value'])) {
            // Placeholder is filled in after the slug is generated by the service.
            $data['value'] = null;
        }

        $block = $this->templates->addBlock($template, $data);

        if ($block->is_dynamic && ! $block->value) {
            $block->update(['value' => '{{'.$block->slug.'}}']);
        }

        return response()->json($block, 201);
    }

    public function update(TemplateBlockRequest $request, TemplateBlock $block): JsonResponse
    {
        $data = $request->safe()->except('image');

        if ($request->hasFile('image')) {
            if ($block->type->value === 'image' && $block->value && ! $block->is_dynamic) {
                Storage::disk('public')->delete($block->value);
            }
            $data['value'] = $request->file('image')->store('blocks', 'public');
        }

        $block->update($data);

        return response()->json($block);
    }

    public function destroy(TemplateBlock $block): JsonResponse
    {
        if ($block->is_default) {
            return response()->json(['message' => 'Default blocks cannot be removed. Hide them instead.'], 422);
        }

        $block->delete();

        return response()->json(['message' => 'Block removed.']);
    }
}
